# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "../vagrantbox/packer_dxe_virtualbox.box"

  config.ssh.username = "ubuntu"
  config.ssh.password = "ubuntu"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox"
end
